add_definitions(-DNODE_EDITOR_SHARED -DNODE_EDITOR_EXPORTS)
if(QV2RAY_QNODEEDITOR_PROVIDER STREQUAL "module")
    set(QNODEEDITOR_DIR ${CMAKE_SOURCE_DIR}/3rdparty/QNodeEditor)
    add_subdirectory(${QNODEEDITOR_DIR} EXCLUDE_FROM_ALL)
    set(QNODEEDITOR_LIBRARY nodes)
elseif(QV2RAY_QNODEEDITOR_PROVIDER STREQUAL "package")
    find_package(NodeEditor REQUIRED CONFIG)
    find_path(QNODEEDITOR_INCLUDE_PATH Node.hpp PATH_SUFFIXES nodes/internal)
    set(QNODEEDITOR_LIBRARY NodeEditor::nodes)
endif()